### ISSUE TITLE
chevauchement texte/image barre lattérale

### ISSUE THREAD

**Issue by AmelieVRL** [CDSP-SCPO/site-DIME-SHS#21]
tout est dans le titre! C'est sur l'actu des médailles CNRS.
![capture d ecran 2018-07-26 a 11 14 24](https://user-images.githubusercontent.com/37452370/43253408-308e5844-90c5-11e8-96a1-936cd323feed.png)

Chez toi, ca passe bien?

**Comment by thom4parisot** [comment]
Chez moi ça passe bien mais c'est parce que le contenu principal est plus long.

Je faisais un traitement spécial pour que la fin de la dernière note soit alignée sur la fin du dernier paragraphe.

Je ferai en sorte de décaler les notes de bas de page à la suite de l'image si ça te va.

**Comment by thom4parisot** [comment]
Je crois qu'avec #20 ce problème n'apparaît plus avec les actualités.

Sinon je regarderai plus en détails en me branchant sur un grand écran.

**Comment by AmelieVRL** [comment]
Le problème de chevauchement est aussi présent dans les pages équipe et beQuali:
![capture d ecran 2018-08-02 a 08 10 58](https://user-images.githubusercontent.com/37452370/43565730-ff8ed89c-962b-11e8-9307-5c725307a5ae.png)
![capture d ecran 2018-08-02 a 08 11 46](https://user-images.githubusercontent.com/37452370/43565822-7e1f340e-962c-11e8-9fed-63a6ecf8fc71.png)


Et sans chevauchement mais peut être issu du même problème, les notes ne sont pas affichées au bon niveau dans la page Bilan (bug aléatoire... mais pas d'affaire de cache, je suis chez moi et c'est la première fois que je consulte le site sur cet ordi) :
![capture d ecran 2018-08-02 a 08 11 22](https://user-images.githubusercontent.com/37452370/43565765-2ebbaa82-962c-11e8-9f50-98e3525a8dce.png)

**Comment by thom4parisot** [comment]
Celui-là, je sens qu'il est lié à #50 et à la nouvelle approche que je proposais d'aborder pour traiter les notes latérales.

@AmelieVRL  Ça te va si on ferme l'issue et qu'on en reparle dans #50 ?

**Comment by AmelieVRL** [comment]
oui ok
