### ISSUE TITLE
Gestion des listes en sidebar

### ISSUE THREAD

**Issue by AmelieVRL** [CDSP-SCPO/site-DIME-SHS#22]
Il semblerait que les listes ne soient pas gérées en sidebar.
![capture d ecran 2018-07-26 a 11 35 21](https://user-images.githubusercontent.com/37452370/43254661-2e6b0c26-90c8-11e8-9a4b-85dac69db03b.png)

**Comment by thom4parisot** [comment]
@AmelieVRL Je ne suis pas tout à fait sûr mais je crois qu'il faut une ligne vide entre "Membres du conseil scientifique" et la première puce pour que ça soit interprété comme une liste.

**Comment by thom4parisot** [comment]
Du coup je ferme parce que tu disais toute à l'heure que c'était OK pour toi.

Les histoires d'ajustements vertical se gèrent dans #21.
