### ISSUE TITLE
Navigation en anglais

### ISSUE THREAD

**Issue by AmelieVRL** [CDSP-SCPO/site-DIME-SHS#25]
Actuellement, il n'y a que publication qui remonte dans le menu en anglais

**Comment by thom4parisot** [comment]
Quand tu disais :

> <amelie_vrl>	le menu en anglais fonctionne mais pas la page outils

tu voulais dire que la page outil ne fonctionne pas bien par rapport au menu anglais ? Ou tu voulais dire qu'elle ne fonctionne pas comme prévu ?

Si c'est ce dernier point, ça va se passer dans #8.

**Comment by thom4parisot** [comment]
(ou alors tu veux parler des libellés de section qui sont en français même sur la version anglaise)

<img width="970" alt="image" src="https://user-images.githubusercontent.com/138627/43276994-f689239e-9106-11e8-8e8c-c2ee5364f3ca.png">

**Comment by AmelieVRL** [comment]
Je voulais dire qu'elle ne montait pas...;)

Le jeudi 26 juillet 2018, Thomas Parisot <notifications@github.com> a
écrit :
> Quand tu disais :
>
> <amelie_vrl> le menu en anglais fonctionne mais pas la page outils
>
> tu voulais dire que la page outil ne fonctionne pas bien par rapport au
menu anglais ? Ou tu voulais dire qu'elle ne fonctionne pas comme prévu ?
>
> Si c'est ce dernier point, ça va se passer dans #8.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/AVHnAp1WTLZtE1lu2vOzd9ouJgzWnpXoGMYCw1vg9D-tiuTX-cQk4x3d3gG14oCqLgAw1UnF3806cbdyz6cUlxVm0Mo647_HlejVpknU7JKD44m9DkaE-XJ1CGf_3eW8kfBxFVyEm8s2msFE1aydh2V5hkJvbA=s0-d-e1-ft#https://github.com/notifications/beacon/Ajt6UlUHeX92tWfZZeryeP4mMrnxw2U5ks5uKfaTgaJpZM4Vh31M.gif
>

-- 

Amélie Vairelles
Chargée de communication
[image: Sciences Po]
CDSP | Médialab
27 rue Saint-Guillaume 75337 Paris cedex 07 France
T. +33 (0)1 45 49 52 75
amelie.vairelles@sciencespo.fr
www.sciencespo.fr
[image: Twitter Sciences Po] <https://twitter.com/sciencespo>
<https://www.facebook.com/sciencespo>
<https://www.linkedin.com/edu/school?id=12454>

**Comment by thom4parisot** [comment]
@AmelieVRL c'est bon sur ce point pour toi ou tu as vu des choses à rectifier ? (j'ai fait un tour rapide sans rien remarquer de flagrant).

**Comment by AmelieVRL** [comment]
a priori, c'est bon pour moi.

**Comment by thom4parisot** [comment]
Cool 🙂
