### ISSUE TITLE
stats et  redirections

### ISSUE THREAD

**Issue by thom4parisot** [CDSP-SCPO/site-DIME-SHS#51]
Plusieurs points sur lesquels apporter des réponses :

- [ ] répondre à "Pour les stats web il y a un Piwik (Matomo maintenant) au CDSP qui est utilisé pour tous les autres sites DIME-SHS, c'est la solution "autonomie" . Si ça vous intéresse je peux fournir le petit code JS à intégrer."
- [ ] répondre à "Pour les redirections, si c'est possible de les avoir au format nginx ça serait cool, sinon un CSV ça ira bien :)"
- [ ] répondre à la question "est-ce que vous pensez qu'il y a moyen de faire la vraie mise en prod avant la fin du mois ? ou ce sera obligatoirement en septembre ?"

Exemple de config nginx:

```nginx
rewrite ^/dime-shs/ancienne-uri/ http://www.sciencespo.fr/dime-shs/nouvelle-uri permanent;
```

**Comment by paulgirard** [comment]
Pour le script Piwik on peut s'en occuper merci de l'avoir resorti.

Pour les redirections, ce n'est pas à toi de faire ça.
L'équipe interne qui a géré l'ancien site doit faire ça (à vori comment le faire dpeuis github ou en amont de la redirection)

**Comment by paulgirard** [comment]
A propos des redirections : 
https://help.github.com/articles/redirects-on-github-pages/

**Comment by AmelieVRL** [comment]
tu veux que je fasse le tableau de redirections?

Amélie
2018-09-07 14:00 GMT+02:00 Paul Girard <notifications@github.com>:
