### ISSUE TITLE
Rendre la branche prod déployable sur l'infrastructure de production

### ISSUE THREAD

**Issue by thom4parisot** [CDSP-SCPO/site-DIME-SHS#52]
Dixit Jérémy :

> Thomas, j'aurai besoin que ce fichier https://github.com/CDSP-SCPO/site-DIME-SHS/blob/master/.gitlab-ci.yml  se retrouve dans la branche prod, mais je ne connais pas trop Travis donc je ne sais pas trop s'il vaut mieux laisser Travis le copier à chaque fois ou si c'est plus propre de le "commiter" directement dans la branche prod ? Je veux bien ton avis...

**Comment by paulgirard** [comment]
On peut mettre de côté.
Nous avons suspendu l'option hébergement en interne car Jérémy est en congés tout le mois de Septembre. On hébergera sur Github directement.

**Comment by thom4parisot** [comment]
Ça marche 👍
