### ISSUE TITLE
2 clics sur le même bouton, ca ne renvoie pas vraiment au niveau de l'ancre

### ISSUE THREAD

**Issue by thom4parisot** [CDSP-SCPO/site-DIME-SHS#58]
@AmelieVRL dit 

> Par contre je viens de remarquer que quand tu clique 2 fois de suite sur le bouton, ca ne renvoie pas vraiment au niveau de l'ancre (surtout visible là où il y a la navigation en colonne de gauche).

via https://github.com/CDSP-SCPO/site-DIME-SHS/pull/31#issuecomment-424299836

**Comment by thom4parisot** [comment]
Potentiellement résolu par #58

**Comment by AmelieVRL** [comment]
Oui en effet, ça fonctionne!
