### ISSUE TITLE
Contribuer des modifs sur le css sans avoir hugo extended

### ISSUE THREAD

**Issue by thom4parisot** [CDSP-SCPO/site-DIME-SHS#59]
@boogheta dit : 

> L'idée n'est pas de l'utiliser de manière systématique, mais uniquement pour pouvoir contribuer à des petites modifs sur le css sans avoir hugo extended. Je voulais vérifier que cela n'avait pas d'impact (a priori j'ai l'impression que la seule différence entre les css générés est la précision après la virgule pour les pourcentage de type 6,6667%), mais j'ai l'impression que les content dans resources/_gen/assets/scss ne sont pas à jour dans le repo justement, tu peux vérifier et les commiter le cas échéant ?

Via https://github.com/CDSP-SCPO/site-DIME-SHS/pull/41#issuecomment-423934139

**Comment by boogheta** [comment]
Hello!
J'ai vu que tu avais regroupé les deux css par langue en un seul et pushé les dernières modifs.
J'ai testé la méthode proposée avec node-sass du coup, et je confirme que le css généré ne diffère de celui généré avec hugo extended qu'en un seul point (sur une demie-douzaine de lignes) pour la précision des pourcentages du type 1/3 et 2/3, pour le reste aucune différence.
À mes yeux ça semble donc une solution acceptable pour pouvoirr intervenir ponctuellement sans nécessiter d'investir plus de temps en investigation ou développement, auquel cas peut-etre juste ajouter la méthode avec node-sass dans la doc voire ajouter une task npm alias.

**Comment by thom4parisot** [comment]
Ça sera résolu par #62 et #63.
