### ISSUE TITLE
Configurer la 404 bilingue du côté du serveur web

### ISSUE THREAD

**Issue by thom4parisot** [CDSP-SCPO/site-DIME-SHS#72]
```
location / {        
  error_page 404 /404.html;
}

location /en {
  error_page 404 /en/404.html;
}
```

**Comment by thom4parisot** [comment]
Salut @jri-sp, ceci est un extrait du fichier de config Nginx pour router l'erreur 404 différemment — si une personne est sur le site en langue française (base `/`) ou si en langue anglaise (base `/en/`).

Est-ce qu'il est possible de le paramétrer en prod pour que ça respecte une telle condition ?

Merci d'avance :-)

**Comment by thom4parisot** [comment]
@AmelieVRL j'ai mis en description d'issue la marche à suivre pour que la page 404 FR/EN créée dans #57 soit appelée dans le bon cas de figure.

Je peux me mettre une alerte dans l'agenda pour me synchroniser avec Jérémy à son retour de vacances, si ça te parait plus simple à gérer de cette manière (je ne me rends pas compte si @jri-sp vérifie ses notifications GitHub ou autre).

**Comment by jri-sp** [comment]
Bonjour à tous, 
Le site est hébergé sur Github Pages:
```
➜  ~ nslookup dime-shs.sciencespo.fr
Server:		10.102.101.10
Address:	10.102.101.10#53

dime-shs.sciencespo.fr	canonical name = cdsp-scpo.github.io.
Name:	cdsp-scpo.github.io
Address: 185.199.108.153
Name:	cdsp-scpo.github.io
Address: 185.199.111.153
Name:	cdsp-scpo.github.io
Address: 185.199.109.153
Name:	cdsp-scpo.github.io
Address: 185.199.110.153
```

Donc je ne sais pas trop si c'est possible, je vais regarder dans leur doc...
Sinon il faudra peut-être migrer le site ailleurs pour pouvoir faire ça, ou faire une 404 commune aux deux langues.

**Comment by thom4parisot** [comment]
Ah !

J'étais resté sur le fait qu'un GitLab prenait le relais du côté CDSP, et publiait la branche "prod" quelque part ailleurs. Merci, c'est noté 🙂 

Sur GitHub Pages, on a droit à "une seule" page 404 en effet. @AmelieVRL, on la rend bilingue, ou tu veux procéder autrement ?

Merci @jri-sp 👍

**Comment by AmelieVRL** [comment]
OK pour une seule page bilingue.
Tu vas killer laquelle?

**Comment by thom4parisot** [comment]
Il n'y a plus qu'une seule page désormais https://github.com/CDSP-SCPO/site-DIME-SHS/blob/master/content/404.md.
